# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="CC BY-NC"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/Lordmau5/FFS" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="ffs" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="3.0.0" #mandatory
 # A display name for the mod
displayName="Fancy Fluid Storage" #mandatory
# A text field displayed in the mod UI
authors="Lordmau5, maxpowa, Gigabit101" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
A simple fluid storage mod that's gonna fancy up your world!
'''